#!/usr/bin/env python3
"""
tools/sync_data_js.py
Canonical Data Synchronization Tool for Ashtavadhanam Modern.

Architecture:
    content/data.json  (Canonical Single Source of Truth)
           │
           ▼
    tools/sync_data_js.py
           │
           ▼
       js/data.js      (Generated standalone JS object for file:/// execution)

Rules:
1. content/data.json is NEVER modified by this tool.
2. js/data.js is generated deterministically.
3. Preserves window.ASHTAVADHANAM_DATA interface.
4. Supports --check mode for automated CI/regression testing.
"""

import os
import sys
import json

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
CANONICAL_JSON_PATH = os.path.join(PROJECT_DIR, "content", "data.json")
TARGET_JS_PATH = os.path.join(PROJECT_DIR, "js", "data.js")

HEADER_COMMENT = """// =============================================================================
// ASHTAVADHANAM MODERN — GENERATED MASTER DATA MODULE
// CANONICAL SOURCE: content/data.json
// GENERATED BY: tools/sync_data_js.py
// DO NOT EDIT MANUALLY — MAKE CHANGES TO content/data.json AND RUN THIS TOOL.
// =============================================================================

window.ASHTAVADHANAM_DATA = """

def generate_js_content(data_dict):
    formatted_json = json.dumps(data_dict, indent=2, ensure_ascii=False)
    return HEADER_COMMENT + formatted_json + ";\n"

def sync(check_only=False):
    if not os.path.exists(CANONICAL_JSON_PATH):
        print(f"ERROR: Canonical data file not found: {CANONICAL_JSON_PATH}")
        sys.exit(1)

    with open(CANONICAL_JSON_PATH, "r", encoding="utf-8") as f:
        try:
            canonical_data = json.load(f)
        except json.JSONDecodeError as e:
            print(f"ERROR: Canonical JSON is invalid: {e}")
            sys.exit(1)

    expected_js_content = generate_js_content(canonical_data)

    if check_only:
        if not os.path.exists(TARGET_JS_PATH):
            print(f"DRIFT DETECTED: {TARGET_JS_PATH} does not exist.")
            sys.exit(1)
        with open(TARGET_JS_PATH, "r", encoding="utf-8") as f:
            current_js_content = f.read()
        if current_js_content != expected_js_content:
            print(f"DRIFT DETECTED: js/data.js is out of sync with content/data.json.")
            print(f"Run 'python tools/sync_data_js.py' to synchronize.")
            sys.exit(1)
        else:
            print("OK: js/data.js is 100% synchronized with content/data.json.")
            sys.exit(0)

    # Perform synchronization
    with open(TARGET_JS_PATH, "w", encoding="utf-8") as f:
        f.write(expected_js_content)

    print(f"SUCCESS: Synchronized {TARGET_JS_PATH} from {CANONICAL_JSON_PATH}.")
    print(f"Keys synchronized: {list(canonical_data.keys())}")
    print(f"Total rounds: {len(canonical_data.get('pages', []))}")
    print(f"Credits present: {'credits' in canonical_data}")
    print(f"Help present: {'help' in canonical_data}")

if __name__ == "__main__":
    check_mode = "--check" in sys.argv
    sync(check_only=check_mode)
